### ISSUE TITLE
Arrivals failing to load for all stops

### ISSUE THREAD

**Issue by jacob-g** [jacob-g/cleveland-rta-next-bus-train#116]
All stops are just showing "N/A".

**Comment by jacob-g** [comment]
Getting the following error:
```
08-19 14:48:24.775 17126-17158/? W/System.err: org.json.JSONException: No value for stops
08-19 14:48:24.777 17126-17158/? W/System.err:     at org.json.JSONObject.get(JSONObject.java:389)
        at org.json.JSONObject.getJSONArray(JSONObject.java:584)
        at org.futuresight.clevelandrtanextbustrain.NetworkController.getStopTimes(NetworkController.java:223)
        at org.futuresight.clevelandrtanextbustrain.NetworkController.getStopTimes(NetworkController.java:178)
        at org.futuresight.clevelandrtanextbustrain.NextBusTrainActivity$GetTimesTask.doInBackground(NextBusTrainActivity.java:827)
        at org.futuresight.clevelandrtanextbustrain.NextBusTrainActivity$GetTimesTask.doInBackground(NextBusTrainActivity.java:797)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by jacob-g** [comment]
This ended up happening because the RTA changed the format of the JSON API. Push this to release as soon as possible. However, #117 is important as a long-term solution to this problem.
